#PE_Q2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib = []
fib_0_init = 1
fib_1_init = 2

#while fib[n] < 4000000:
#	fib[n] = fib[n] + fib[n-1]

def fib(n):


	
