#PE_Q2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib = []
fib_fin = 0
x = 2
y = 1
z = 0

#Initial Conditions
fib.append(y)
fib.append(x)

while z < 4000000:
	z = x + y
	fib.append(z)
	y = x 
	x = z

for i in range(len(fib)):
	if fib[i] % 2 == 0:
		fib_fin += fib[i]

print fib_fin